### ISSUE TITLE
Upgrading to 5.3 breaks down completely

### ISSUE THREAD

**Issue by ionelmc** [explorerhq/sql-explorer#693]
Seems the new user-configurable connections have broken migrations - even trying to list the connections will fail with something like:

```
[2024-12-19 15:02:09.399] django.request (ERROR) Internal Server Error: /manage/explorer/databaseconnection/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/contrib/admin/options.py", line 2065, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.12/dist-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/db/models/query.py", line 121, in __iter__
    for row in compiler.results_iter(results):
  File "/usr/local/lib/python3.12/dist-packages/django/db/models/sql/compiler.py", line 1500, in apply_converters
    value = converter(value, expression, connection)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django_cryptography/fields.py", line 182, in from_db_value
    return self._load(force_bytes(value))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django_cryptography/fields.py", line 120, in _load
    return pickle.loads(self._fernet.decrypt(value, self.ttl))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django_cryptography/utils/crypto.py", line 160, in decrypt
    data = self.signer.unsign(data, ttl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django_cryptography/core/signing.py", line 324, in unsign
    raise BadSignature('Signature "%r" does not match' % binascii.b2a_base64(sig))
django.core.signing.BadSignature: Signature "b'......\n'" does not match
```

I have these versions:
```
django==4.2.17 
django-cryptography-django5==2.2 
django-sql-explorer==5.3 
```

Sadly enough this is hard to clean up manually as even `DatabaseConnection.objects.all().delete()` fails with:
```
>>> DatabaseConnection.objects.all().delete()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.12/dist-packages/django/db/models/query.py", line 1147, in delete
    collector.collect(del_query)
  File "/usr/local/lib/python3.12/dist-packages/django/db/models/deletion.py", line 284, in collect
    new_objs = self.add(
               ^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/db/models/deletion.py", line 126, in add
    if not objs:
           ^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/db/models/query.py", line 412, in __bool__
    self._fetch_all()
  File "/usr/local/lib/python3.12/dist-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django/db/models/query.py", line 121, in __iter__
    for row in compiler.results_iter(results):
  File "/usr/local/lib/python3.12/dist-packages/django/db/models/sql/compiler.py", line 1500, in apply_converters
    value = converter(value, expression, connection)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django_cryptography/fields.py", line 182, in from_db_value
    return self._load(force_bytes(value))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django_cryptography/fields.py", line 120, in _load
    return pickle.loads(self._fernet.decrypt(value, self.ttl))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django_cryptography/utils/crypto.py", line 160, in decrypt
    data = self.signer.unsign(data, ttl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/django_cryptography/core/signing.py", line 324, in unsign
    raise BadSignature('Signature "%r" does not match' % binascii.b2a_base64(sig))
django.core.signing.BadSignature: Signature "b'......\n'" does not match
```
(i have removed the signature value from the tracebacks, it was a base64 encoded value if it matters)

So going forward I have truncated the explorer_querylog and explorer_databaseconnection tables using dbshell and I am trying to see what is allowed in /manage/explorer/databaseconnection/add/ and to my dismay I see that everything is allowed, and the extra field doesn't even have a help_text to indicate what sort of value should be there. First off, I think that while this might be useful for some projects, it's a terrible idea to allow users to connect to anything, with any connection option they like in general. I would like to have a restricted mode that worked exactly like in 5.2.0, something that completely restricts users and available connections only come from settings. Yes, superuser in django admin == user. It's still an user, sorry. I don't want superusers do bad stuff :-)

**Comment by chrisclark** [comment]
hi there - sorry for the trouble! I'm not totally sure what the problem is re: the error trace. I will think about it...

As for connection management, that is a configurable permission. See this bit of code:
https://github.com/explorerhq/sql-explorer/blob/master/explorer/app_settings.py#L74

You can simply set:
`EXPLORER_PERMISSION_CONNECTIONS = lamba u: false`
in your settings file to restrict users from connection management.

I agree the 'extras' thing is a bit nasty. I'll think about how to improve. The idea behind it is to support a variety of 'long tail' DB drivers for django (see: MS SQL Server) that might have weird additional connection parameters. But yeah, I don't love it either.

**Comment by ernstki** [comment]
We attempted to bring SQL Explorer online in a local development environment, using a SQL dump from another server. The original server's `SECRET_KEY` is stored in some infrastructure I don't have access to, which leads to this error when I use a locally-generated one.

It looks like `explorer_databaseconnection.host` has been encrypted since [probably 4.4.0b1](https://github.com/explorerhq/sql-explorer/commit/6f573956f1ab735fcc94e46356edefb43587df20#diff-4c8f5c22a19f5e98a38d53383298194da654638d69e2b01105ce841dc8d3f210R29-R31). I guess I wasn't paying attention, or hadn't rotated keys in the meantime.

```console
mysql> select * from explorer_databaseconnection;
+----+----------+-------------------+------+------+----------+-----------------…
| id | alias    | engine            | name | user | password | host            
+----+----------+-------------------+------+------+----------+-----------------…
|  1 | readonly | django_connection | NULL | NULL | NULL     | 0x80000000006A24…
+----+----------+-------------------+------+------+----------+-----------------…
1 row in set (0.00 sec)
```

The encrypted `host` column is trouble for _us_, but I think I understand @chrisclark's reasoning, since he's operating SQL Explorer as a SaaS now, where this makes sense.

If your circumstances match mine, and you _know_ the database hostname — it's right there in your `settings.py` or `.env` or whatever, after all — you can fix this situation with a bit of Python. Let's assume you have only **a single `EXPLORER_CONNECTIONS` connection** defined, and your database hostname is is coming from an environment variable, like so:

```python
DATABASES = {
    # ⋮
    "readonly": {
        # ⋮
        "HOST": os.environ.get("DB_HOST"),
        # ⋮
    },
}

EXPLORER_CONNECTIONS = {"Default": "readonly"}
EXPLORER_DEFAULT_CONNECTION = "readonly"
```

Run this as a one-liner with `python -c` or in `manage.py shell` to re-encrypt that single column with your new `SECRET_KEY`:

```python
# tested with django==6.0.*, django-sql-explorer==5.3, MySQL 8.4.x
import os
import django; django.setup()
from django.db import connection
from explorer.models import DatabaseConnection;
f = DatabaseConnection._meta.get_field("host")
b = f.get_db_prep_value(os.environ.get("DB_HOST"), connection)  # bytes
connection.cursor().execute("""
    UPDATE explorer_databaseconnection SET host = %s
    WHERE id = %s
""", (b, 1))
```

Assuming you're running the Django development server, refresh the browser, and you should be back in business. Hope that helps someone!

**Comment by ernstki** [comment]
@ionelmc Can you confirm whether you used the same `SECRET_KEY` before as after you migrated to 5.3? If they were in fact different, then I suspect we can close this issue. There isn't much else that could be done about that, short of manually fixing the connection table as described [above](https://github.com/explorerhq/sql-explorer/issues/693#issuecomment-5706586984).

I think Chris's previous comment should address specific concerns you had about random users being able to make random connections, or if not, perhaps a separate issue could be created for that.
